fix(ci): the github action to build and test Node.js version 16 does not work.
Error:
- Gets an error because the default npm script 'test' is also not allowed.
Error: no test has been specified.
https://github.com/beatrizsmerino/vue-editor/actions/runs/1693087967

Solution:
- Remove the npm script 'test' from the 'package.json' file.
- Check if the npm script 'test' exists before launching it.