fix(config): `eslint` error on push files by `husky`
Error:
- Error: Cannot read config file: /Users/beatrizsmerino/Sites/localhost/vue-editor/vite-project/.eslintrc.cjs
Error: Cannot find module '@rushstack/eslint-patch/modern-module-resolution'

Solution:
- Add the `vite-project` folder to the config files to ignore the execution of `prettier`, `eslint` and `stylelint` in it.
The reason for this is to avoid a husky error when pushing files to the repository.